spring.application.name=firstproject
spring.datasource.url=jdbc:postgresql://dpg-d71tlh5m5p6s73a1bte0-a/mydatabase_ihry?sslmode=require
spring.datasource.username=mydatabase_ihry_user
spring.datasource.password=btgjdb5vT0uAaDzQbrvy14nW2TKEosFa
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=ThisIsADevelopmentOnlySecretKeyForComplaintSystemChangeInProd12345
app.jwt.expiration-ms=86400000