spring.application.name=firstproject

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d71tlh5m5p6s73a1bte0-a.oregon-postgres.render.com:5432/mydatabase_ihry?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:mydatabase_ihry_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:btgjdb5vT0uAaDzQbrvy14nW2TKEosFa}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=ThisIsADevelopmentOnlySecretKeyForComplaintSystemChangeInProd12345
app.jwt.expiration-ms=86400000